<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Expected text Sapphire matches actual test Sapphire]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="69513" started-at="2014-04-30T11:55:46Z" finished-at="2014-04-30T11:56:56Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="69513" started-at="2014-04-30T11:55:46Z" finished-at="2014-04-30T11:56:56Z">
      <class name="com.sapphire.portfolio.Port_Create_SA_aers">
        <test-method status="PASS" signature="doLogIn()[pri:0, instance:com.sapphire.portfolio.Port_Create_SA_aers@87a5cc]" name="doLogIn" is-config="true" duration-ms="14829" started-at="2014-04-30T17:25:46Z" finished-at="2014-04-30T17:26:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogIn -->
        <test-method status="FAIL" signature="TestMethodPortCreateSAaers()[pri:0, instance:com.sapphire.portfolio.Port_Create_SA_aers@87a5cc]" name="TestMethodPortCreateSAaers" duration-ms="45115" started-at="2014-04-30T17:26:01Z" finished-at="2014-04-30T17:26:46Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error in creating topic Alerts for sa aers ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error in creating topic Alerts for sa aers 
	at org.testng.Assert.fail(Assert.java:94)
	at com.sapphire.portfolio.Port_Create_SA_aers.TestMethodPortCreateSAaers(Port_Create_SA_aers.java:159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Expected text Sapphire matches actual test Sapphire]]>
            </line>
          </reporter-output>
        </test-method> <!-- TestMethodPortCreateSAaers -->
        <test-method status="PASS" signature="doLogOut()[pri:0, instance:com.sapphire.portfolio.Port_Create_SA_aers@87a5cc]" name="doLogOut" is-config="true" duration-ms="9558" started-at="2014-04-30T17:26:46Z" finished-at="2014-04-30T17:26:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogOut -->
      </class> <!-- com.sapphire.portfolio.Port_Create_SA_aers -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
